# Generated by Django 4.0.4 on 2022-04-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0003_user_is_diocese_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_diocese',
            field=models.BooleanField(default=False),
        ),
    ]
