# Generated by Django 4.0.4 on 2022-04-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0005_remove_user_is_diocese_user_anglican_user_church_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('', '---Select your Sex---'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divccon.province'),
        ),
    ]
