# Generated by Django 4.0.4 on 2022-04-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0006_province_alter_user_sex_alter_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
