# Generated by Django 4.0.4 on 2022-05-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0008_alter_province_name_alter_user_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='anglican',
            field=models.CharField(choices=[('', '---Are you an Anglican?---'), ('ANGLICAN', 'YES - ANGLICAN'), ('NON-ANGLICAN', 'NO - NON-ANGLICAN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('', '---Where are you located?---'), ('NIGERIA', 'NIGERIA'), ('ABROAD', 'ABROAD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='divccon.province'),
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('province', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='divccon.province')),
            ],
        ),
    ]
