# Generated by Django 4.0.4 on 2022-05-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0009_sex_alter_user_anglican_alter_user_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sex',
        ),
    ]
