# Generated by Django 4.0.4 on 2022-05-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0011_church_alter_user_diocese'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Church',
        ),
        migrations.AlterField(
            model_name='user',
            name='diocese',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(choices=[('', '---Where are you located?---'), ('NIGERIA', 'NIGERIA'), ('ABROAD', 'ABROAD')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Diocese',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
