# Generated by Django 4.0.4 on 2022-05-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0013_remove_user_user_photo_user_photo_alter_user_church_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='NONE', upload_to='images/'),
        ),
    ]
