# Generated by Django 4.0.4 on 2022-05-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0016_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
