# Generated by Django 4.0.4 on 2022-05-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0017_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
