# Generated by Django 4.0.4 on 2022-05-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0022_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
