# Generated by Django 4.0.4 on 2022-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divccon', '0023_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
